ocr_client_cfg:
  s3_info:
    endpoint:   "http://s3.amazonaws.com"
    command:    "download"
    bucketname: "libhub-readme"
    download_dir: "/cnvrg"
    prefix:       "pdf_extraction_data/"
    key_id:       "some__ID__ID"
    secret_key:   "some_secret_secret"
  httplinks:
    - "https://libhub-readme.s3.us-west-2.amazonaws.com/pdf_extraction_data/Data+science.pdf"
    - "https://libhub-readme.s3.us-west-2.amazonaws.com/pdf_extraction_data/economics.pdf"
  files:
    - "/cnvrg/Data+science.pdf"
    - "/cnvrg/economics.pdf"
  service_network:
    remote_service_address: "172.17.0.3"
    remote_service_port:  "50051"
  service_network_rest:
    remote_service_address: "172.17.0.3"
    remote_service_port:  "40051"
  service_network_gateway:
    remote_service_address: "172.17.0.3"
    remote_service_port:  "8081"



