export HOME_ROOT="/root/ocr_service_backend/s3_connector"



export PYTHONPATH=${HOME_ROOT}

export LOCAL_SERVER_PORT=50051
export S3_SERVICE_ADDRESS=${S3_SERVICE_SERVICE_HOST:-"172.17.0.2"}
export OCR_SERVICE_ADDRESS=${OCR_SERVICE_SERVICE_HOST:-"172.17.0.3"}

echo HOME_ROOT=${HOME_ROOT}
echo PYTHONPATH${PYTHONPATH}
echo LOCAL_SERVER_PORT=${LOCAL_SERVER_PORT}
echo S3_SERVICE_ADDRESS=${S3_SERVICE_ADDRESS}
