# Default values for ocr
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: lamatriz
  name: wlpu
  tag: ubuntu_20.04_ocr_worker_MVP_Set1_v3
  pullPolicy: Always

testDemo:
  image:
    repository: lamatriz
    name: wlpu
    tag: ubuntu_20.04_MVP_client_v3
    pullPolicy: Always

service:
  type: NodePort
  name: s-fastapi
  port: 40051
  targetPort: 40051
  name2: s-grcp
  port2: 50051
  targetPort2: 50051
  annotations: {}
gracePeriod: 5

namespace: mldev

resources:
  limits:
    cpu: 8
  requests:
    cpu: 4

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
