# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: s3connect.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fs3connect.proto\x12\ts3connect\"A\n\x05S3env\x12\x19\n\x11\x61ws_access_key_id\x18\x01 \x01(\t\x12\x1d\n\x15\x61ws_secret_access_key\x18\x02 \x01(\t\"\x8d\x01\n\x06S3args\x12\x10\n\x08\x65ndpoint\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x12\n\nbucketname\x18\x03 \x01(\t\x12\x11\n\x04\x66ile\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06prefix\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x10\n\x08localdir\x18\x06 \x01(\tB\x07\n\x05_fileB\t\n\x07_prefix\"K\n\tS3request\x12\x1f\n\x04\x61rgs\x18\x01 \x01(\x0b\x32\x11.s3connect.S3args\x12\x1d\n\x03\x65nv\x18\x02 \x01(\x0b\x32\x10.s3connect.S3env\"O\n\nS3response\x12\"\n\x07request\x18\x01 \x01(\x0b\x32\x11.s3connect.S3args\x12\x0e\n\x06status\x18\x02 \x01(\x05\x12\r\n\x05\x66iles\x18\x03 \x03(\t\"B\n\x0fS3FilesResponse\x12\x12\n\x08\x66ilename\x18\x01 \x01(\tH\x00\x12\x0e\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x00\x42\x0b\n\tfile_info2\x97\x01\n\ts3connect\x12H\n\x17\x44ownloadFilesToLocation\x12\x14.s3connect.S3request\x1a\x15.s3connect.S3response\"\x00\x12@\n\x08GetFiles\x12\x14.s3connect.S3request\x1a\x1a.s3connect.S3FilesResponse\"\x00\x30\x01\x42?\n%io.local_service.local_grpc.s3connectB\x0eS3ConnectProtoP\x01\xa2\x02\x03S3Cb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 's3connect_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%io.local_service.local_grpc.s3connectB\016S3ConnectProtoP\001\242\002\003S3C'
  _S3ENV._serialized_start=30
  _S3ENV._serialized_end=95
  _S3ARGS._serialized_start=98
  _S3ARGS._serialized_end=239
  _S3REQUEST._serialized_start=241
  _S3REQUEST._serialized_end=316
  _S3RESPONSE._serialized_start=318
  _S3RESPONSE._serialized_end=397
  _S3FILESRESPONSE._serialized_start=399
  _S3FILESRESPONSE._serialized_end=465
  _S3CONNECT._serialized_start=468
  _S3CONNECT._serialized_end=619
# @@protoc_insertion_point(module_scope)
