# ocr-app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ocr.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ocr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ocr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ocr.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ include "ocr.fullname" . }}-secret
      containers:
        - name: {{ .Chart.Name }}
          resources: 
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: REST_WORKER_COUNT
            value: {{ .Values.restWorkerCount | quote }}
          command: ["bash", "-c"]
          args:
          - |
            /root/ocr_service_backend/text-extraction/local_service/start_service.sh
          ports:
          - containerPort:  {{ .Values.service.targetPort }}
      terminationGracePeriodSeconds: {{ .Values.gracePeriod }}
