apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImIyRnJkSEpsWlhNNk9EY3lOREV5Wm1VdE9USTJNUzAwWW1VMUxXSmhNak10TURWbVpqbGxOek5rT0RVeCIKCQl9Cgl9Cn0=
metadata:
  name: {{ .Values.imagePullSecret }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson