apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocr.fullname" . }}
  labels:
    {{- include "ocr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
    - port: {{ .Values.service.port2 }}
      targetPort: {{ .Values.service.targetPort2 }}
      protocol: TCP
      name: {{ .Values.service.name2 }}
  selector:
    {{- include "ocr.selectorLabels" . | nindent 4 }}
