apiVersion: v1
kind: Pod
metadata:
  name: client-fe
spec:
  containers:
  - name: client-fe
    image: lamatriz/wlpu:ubuntu_20.04_MVP_client
    command: ["sleep"]
    args: ["1h"]
    imagePullPolicy: Always
    ports:
    - containerPort: 50051
  imagePullSecrets:
  - name: regcred
