apiVersion: v1
kind: Service
metadata:
  name: ocr
spec:
  type: NodePort
  selector:
    app: ocr-be
  ports:
    - port: 50051
      targetPort: 50051
    - port: 40051
      targetPort: 40051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr-be
  template:
    metadata:
      labels:
        app: ocr-be
    spec:
      containers:
      - name: ocr-mvp-set1
        image: gildesh/wlpu:ubuntu_20.04_ocr_MVP_Set1_v3
        command: ["/usr/bin/bash"]
        args: ["-c", "bash /root/ocr_service_backend/text-extraction/local_service/start_service.sh"]
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        - containerPort: 40051
      imagePullSecrets:
      - name: regcred
