apiVersion: v1
kind: Service
metadata:
  name: ocr-service
spec:
  type: NodePort
  selector:
    app: ocr-be
  ports:
    - port: 50051
      targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr-be
  template:
    metadata:
      labels:
        app: ocr-be
    spec:
      containers:
      - name: ocr-mvp-set1
        image: lamatriz/wlpu:ubuntu_20.04_MVP_Set1
        #image: lamatriz/wlpu:poc1_crohn_app
        command: ["/usr/bin/bash"]
        args: ["-c", ". /root/ocr_service_backend/text-extraction/local_service/setup_ocr_requirements.sh"]
        command: ["/usr/bin/bash"]
        args: ["-c", "bash /root/ocr_service_backend/s3_connector/local_service/start_service.sh"]
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
      imagePullSecrets:
      - name: regcred