apiVersion: v1
kind: Service
metadata:
  name: s3-service
spec:
  type: NodePort
  selector:
    app: s3-be
  ports:
    - port: 50051
      targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-be
  template:
    metadata:
      labels:
        app: s3-be
    spec:
      containers:
      - name: s3-mvp-set1
        image: lamatriz/wlpu:ubuntu_20.04_MVP_s3
        command: ["/usr/bin/bash"]
        args: ["-c", ". /root/ocr_service_backend/s3_connector/local_service/setup_s3_requirements.sh; bash /root/ocr_service_backend/s3_connector/local_service/start_service.sh"]

        imagePullPolicy: Always
        ports:
        - containerPort: 50051
      imagePullSecrets:
      - name: regcred
